// ==========================================
// Список стран с телефонными кодами (задача 9)
// ==========================================
// iso — ISO 3166-1 alpha-2, dial — международный телефонный код (без "+"),
// name — русское название для отображения в выборе страны при регистрации.
// Список отсортирован по названию на русском для удобного поиска.

export const COUNTRIES = [
    { iso: 'AU', dial: '61', name: 'Австралия' },
    { iso: 'AT', dial: '43', name: 'Австрия' },
    { iso: 'AZ', dial: '994', name: 'Азербайджан' },
    { iso: 'AX', dial: '358', name: 'Аландские острова' },
    { iso: 'AL', dial: '355', name: 'Албания' },
    { iso: 'DZ', dial: '213', name: 'Алжир' },
    { iso: 'AO', dial: '244', name: 'Ангола' },
    { iso: 'AD', dial: '376', name: 'Андорра' },
    { iso: 'AI', dial: '1264', name: 'Ангилья' },
    { iso: 'AQ', dial: '672', name: 'Антарктида' },
    { iso: 'AG', dial: '1268', name: 'Антигуа и Барбуда' },
    { iso: 'AR', dial: '54', name: 'Аргентина' },
    { iso: 'AM', dial: '374', name: 'Армения' },
    { iso: 'AW', dial: '297', name: 'Аруба' },
    { iso: 'AF', dial: '93', name: 'Афганистан' },
    { iso: 'BS', dial: '1242', name: 'Багамы' },
    { iso: 'BD', dial: '880', name: 'Бангладеш' },
    { iso: 'BB', dial: '1246', name: 'Барбадос' },
    { iso: 'BH', dial: '973', name: 'Бахрейн' },
    { iso: 'BY', dial: '375', name: 'Беларусь' },
    { iso: 'BZ', dial: '501', name: 'Белиз' },
    { iso: 'BE', dial: '32', name: 'Бельгия' },
    { iso: 'BJ', dial: '229', name: 'Бенин' },
    { iso: 'BM', dial: '1441', name: 'Бермуды' },
    { iso: 'BG', dial: '359', name: 'Болгария' },
    { iso: 'BO', dial: '591', name: 'Боливия' },
    { iso: 'BQ', dial: '599', name: 'Бонэйр' },
    { iso: 'BA', dial: '387', name: 'Босния и Герцеговина' },
    { iso: 'BW', dial: '267', name: 'Ботсвана' },
    { iso: 'BR', dial: '55', name: 'Бразилия' },
    { iso: 'BN', dial: '673', name: 'Бруней' },
    { iso: 'BF', dial: '226', name: 'Буркина-Фасо' },
    { iso: 'BI', dial: '257', name: 'Бурунди' },
    { iso: 'BT', dial: '975', name: 'Бутан' },
    { iso: 'VU', dial: '678', name: 'Вануату' },
    { iso: 'VA', dial: '379', name: 'Ватикан' },
    { iso: 'GB', dial: '44', name: 'Великобритания' },
    { iso: 'HU', dial: '36', name: 'Венгрия' },
    { iso: 'VE', dial: '58', name: 'Венесуэла' },
    { iso: 'VG', dial: '1284', name: 'Виргинские о-ва (Брит.)' },
    { iso: 'VI', dial: '1340', name: 'Виргинские о-ва (США)' },
    { iso: 'TL', dial: '670', name: 'Восточный Тимор' },
    { iso: 'VN', dial: '84', name: 'Вьетнам' },
    { iso: 'GA', dial: '241', name: 'Габон' },
    { iso: 'HT', dial: '509', name: 'Гаити' },
    { iso: 'GY', dial: '592', name: 'Гайана' },
    { iso: 'GM', dial: '220', name: 'Гамбия' },
    { iso: 'GH', dial: '233', name: 'Гана' },
    { iso: 'GP', dial: '590', name: 'Гваделупа' },
    { iso: 'GT', dial: '502', name: 'Гватемала' },
    { iso: 'GN', dial: '224', name: 'Гвинея' },
    { iso: 'GW', dial: '245', name: 'Гвинея-Бисау' },
    { iso: 'DE', dial: '49', name: 'Германия' },
    { iso: 'GG', dial: '44', name: 'Гернси' },
    { iso: 'GI', dial: '350', name: 'Гибралтар' },
    { iso: 'HN', dial: '504', name: 'Гондурас' },
    { iso: 'HK', dial: '852', name: 'Гонконг' },
    { iso: 'GD', dial: '1473', name: 'Гренада' },
    { iso: 'GL', dial: '299', name: 'Гренландия' },
    { iso: 'GR', dial: '30', name: 'Греция' },
    { iso: 'GE', dial: '995', name: 'Грузия' },
    { iso: 'GU', dial: '1671', name: 'Гуам' },
    { iso: 'DK', dial: '45', name: 'Дания' },
    { iso: 'JE', dial: '44', name: 'Джерси' },
    { iso: 'DJ', dial: '253', name: 'Джибути' },
    { iso: 'DM', dial: '1767', name: 'Доминика' },
    { iso: 'DO', dial: '1809', name: 'Доминиканская Республика' },
    { iso: 'EG', dial: '20', name: 'Египет' },
    { iso: 'ZM', dial: '260', name: 'Замбия' },
    { iso: 'EH', dial: '212', name: 'Западная Сахара' },
    { iso: 'ZW', dial: '263', name: 'Зимбабве' },
    { iso: 'IL', dial: '972', name: 'Израиль' },
    { iso: 'IN', dial: '91', name: 'Индия' },
    { iso: 'ID', dial: '62', name: 'Индонезия' },
    { iso: 'JO', dial: '962', name: 'Иордания' },
    { iso: 'IQ', dial: '964', name: 'Ирак' },
    { iso: 'IR', dial: '98', name: 'Иран' },
    { iso: 'IE', dial: '353', name: 'Ирландия' },
    { iso: 'IS', dial: '354', name: 'Исландия' },
    { iso: 'ES', dial: '34', name: 'Испания' },
    { iso: 'IT', dial: '39', name: 'Италия' },
    { iso: 'YE', dial: '967', name: 'Йемен' },
    { iso: 'CV', dial: '238', name: 'Кабо-Верде' },
    { iso: 'KZ', dial: '7', name: 'Казахстан' },
    { iso: 'KH', dial: '855', name: 'Камбоджа' },
    { iso: 'CM', dial: '237', name: 'Камерун' },
    { iso: 'CA', dial: '1', name: 'Канада' },
    { iso: 'QA', dial: '974', name: 'Катар' },
    { iso: 'KE', dial: '254', name: 'Кения' },
    { iso: 'CY', dial: '357', name: 'Кипр' },
    { iso: 'KG', dial: '996', name: 'Киргизия' },
    { iso: 'KI', dial: '686', name: 'Кирибати' },
    { iso: 'CN', dial: '86', name: 'Китай' },
    { iso: 'CC', dial: '61', name: 'Кокосовые острова' },
    { iso: 'CO', dial: '57', name: 'Колумбия' },
    { iso: 'KM', dial: '269', name: 'Коморы' },
    { iso: 'CG', dial: '242', name: 'Конго' },
    { iso: 'CD', dial: '243', name: 'Конго (ДРК)' },
    { iso: 'KP', dial: '850', name: 'КНДР (Северная Корея)' },
    { iso: 'KR', dial: '82', name: 'Республика Корея (Южная)' },
    { iso: 'CR', dial: '506', name: 'Коста-Рика' },
    { iso: 'CI', dial: '225', name: 'Кот-д’Ивуар' },
    { iso: 'CU', dial: '53', name: 'Куба' },
    { iso: 'KW', dial: '965', name: 'Кувейт' },
    { iso: 'CW', dial: '599', name: 'Кюрасао' },
    { iso: 'LA', dial: '856', name: 'Лаос' },
    { iso: 'LV', dial: '371', name: 'Латвия' },
    { iso: 'LS', dial: '266', name: 'Лесото' },
    { iso: 'LR', dial: '231', name: 'Либерия' },
    { iso: 'LB', dial: '961', name: 'Ливан' },
    { iso: 'LY', dial: '218', name: 'Ливия' },
    { iso: 'LT', dial: '370', name: 'Литва' },
    { iso: 'LI', dial: '423', name: 'Лихтенштейн' },
    { iso: 'LU', dial: '352', name: 'Люксембург' },
    { iso: 'MU', dial: '230', name: 'Маврикий' },
    { iso: 'MR', dial: '222', name: 'Мавритания' },
    { iso: 'MG', dial: '261', name: 'Мадагаскар' },
    { iso: 'YT', dial: '262', name: 'Майотта' },
    { iso: 'MO', dial: '853', name: 'Макао' },
    { iso: 'MW', dial: '265', name: 'Малави' },
    { iso: 'MY', dial: '60', name: 'Малайзия' },
    { iso: 'ML', dial: '223', name: 'Мали' },
    { iso: 'MV', dial: '960', name: 'Мальдивы' },
    { iso: 'MT', dial: '356', name: 'Мальта' },
    { iso: 'MA', dial: '212', name: 'Марокко' },
    { iso: 'MQ', dial: '596', name: 'Мартиника' },
    { iso: 'MH', dial: '692', name: 'Маршалловы Острова' },
    { iso: 'MX', dial: '52', name: 'Мексика' },
    { iso: 'FM', dial: '691', name: 'Микронезия' },
    { iso: 'MZ', dial: '258', name: 'Мозамбик' },
    { iso: 'MD', dial: '373', name: 'Молдова' },
    { iso: 'MC', dial: '377', name: 'Монако' },
    { iso: 'MN', dial: '976', name: 'Монголия' },
    { iso: 'MS', dial: '1664', name: 'Монтсеррат' },
    { iso: 'MM', dial: '95', name: 'Мьянма' },
    { iso: 'NA', dial: '264', name: 'Намибия' },
    { iso: 'NR', dial: '674', name: 'Науру' },
    { iso: 'NP', dial: '977', name: 'Непал' },
    { iso: 'NE', dial: '227', name: 'Нигер' },
    { iso: 'NG', dial: '234', name: 'Нигерия' },
    { iso: 'NL', dial: '31', name: 'Нидерланды' },
    { iso: 'NI', dial: '505', name: 'Никарагуа' },
    { iso: 'NU', dial: '683', name: 'Ниуэ' },
    { iso: 'NZ', dial: '64', name: 'Новая Зеландия' },
    { iso: 'NC', dial: '687', name: 'Новая Каледония' },
    { iso: 'NO', dial: '47', name: 'Норвегия' },
    { iso: 'AE', dial: '971', name: 'ОАЭ' },
    { iso: 'OM', dial: '968', name: 'Оман' },
    { iso: 'BV', dial: '47', name: 'Остров Буве' },
    { iso: 'IM', dial: '44', name: 'Остров Мэн' },
    { iso: 'NF', dial: '672', name: 'Остров Норфолк' },
    { iso: 'CX', dial: '61', name: 'Остров Рождества' },
    { iso: 'PK', dial: '92', name: 'Пакистан' },
    { iso: 'PW', dial: '680', name: 'Палау' },
    { iso: 'PS', dial: '970', name: 'Палестина' },
    { iso: 'PA', dial: '507', name: 'Панама' },
    { iso: 'PG', dial: '675', name: 'Папуа — Новая Гвинея' },
    { iso: 'PY', dial: '595', name: 'Парагвай' },
    { iso: 'PE', dial: '51', name: 'Перу' },
    { iso: 'PN', dial: '64', name: 'Питкэрн' },
    { iso: 'PL', dial: '48', name: 'Польша' },
    { iso: 'PT', dial: '351', name: 'Португалия' },
    { iso: 'PR', dial: '1787', name: 'Пуэрто-Рико' },
    { iso: 'RE', dial: '262', name: 'Реюньон' },
    { iso: 'RU', dial: '7', name: 'Россия' },
    { iso: 'RW', dial: '250', name: 'Руанда' },
    { iso: 'RO', dial: '40', name: 'Румыния' },
    { iso: 'SV', dial: '503', name: 'Сальвадор' },
    { iso: 'WS', dial: '685', name: 'Самоа' },
    { iso: 'SM', dial: '378', name: 'Сан-Марино' },
    { iso: 'ST', dial: '239', name: 'Сан-Томе и Принсипи' },
    { iso: 'SA', dial: '966', name: 'Саудовская Аравия' },
    { iso: 'SZ', dial: '268', name: 'Свазиленд (Эсватини)' },
    { iso: 'MP', dial: '1670', name: 'Северные Марианские о-ва' },
    { iso: 'MK', dial: '389', name: 'Северная Македония' },
    { iso: 'SC', dial: '248', name: 'Сейшелы' },
    { iso: 'BL', dial: '590', name: 'Сен-Бартелеми' },
    { iso: 'SH', dial: '290', name: 'Святая Елена' },
    { iso: 'KN', dial: '1869', name: 'Сент-Китс и Невис' },
    { iso: 'LC', dial: '1758', name: 'Сент-Люсия' },
    { iso: 'MF', dial: '590', name: 'Сен-Мартен' },
    { iso: 'PM', dial: '508', name: 'Сен-Пьер и Микелон' },
    { iso: 'VC', dial: '1784', name: 'Сент-Винсент и Гренадины' },
    { iso: 'SN', dial: '221', name: 'Сенегал' },
    { iso: 'RS', dial: '381', name: 'Сербия' },
    { iso: 'SG', dial: '65', name: 'Сингапур' },
    { iso: 'SX', dial: '1721', name: 'Синт-Мартен' },
    { iso: 'SY', dial: '963', name: 'Сирия' },
    { iso: 'SK', dial: '421', name: 'Словакия' },
    { iso: 'SI', dial: '386', name: 'Словения' },
    { iso: 'GS', dial: '500', name: 'Южная Георгия' },
    { iso: 'SB', dial: '677', name: 'Соломоновы Острова' },
    { iso: 'SO', dial: '252', name: 'Сомали' },
    { iso: 'SD', dial: '249', name: 'Судан' },
    { iso: 'SR', dial: '597', name: 'Суринам' },
    { iso: 'US', dial: '1', name: 'США' },
    { iso: 'SL', dial: '232', name: 'Сьерра-Леоне' },
    { iso: 'TJ', dial: '992', name: 'Таджикистан' },
    { iso: 'TH', dial: '66', name: 'Таиланд' },
    { iso: 'TW', dial: '886', name: 'Тайвань' },
    { iso: 'TZ', dial: '255', name: 'Танзания' },
    { iso: 'TC', dial: '1649', name: 'Тёркс и Кайкос' },
    { iso: 'TG', dial: '228', name: 'Того' },
    { iso: 'TK', dial: '690', name: 'Токелау' },
    { iso: 'TO', dial: '676', name: 'Тонга' },
    { iso: 'TT', dial: '1868', name: 'Тринидад и Тобаго' },
    { iso: 'TV', dial: '688', name: 'Тувалу' },
    { iso: 'TN', dial: '216', name: 'Тунис' },
    { iso: 'TM', dial: '993', name: 'Туркменистан' },
    { iso: 'TR', dial: '90', name: 'Турция' },
    { iso: 'UG', dial: '256', name: 'Уганда' },
    { iso: 'UZ', dial: '998', name: 'Узбекистан' },
    { iso: 'UA', dial: '380', name: 'Украина' },
    { iso: 'WF', dial: '681', name: 'Уоллис и Футуна' },
    { iso: 'UY', dial: '598', name: 'Уругвай' },
    { iso: 'FO', dial: '298', name: 'Фарерские острова' },
    { iso: 'FJ', dial: '679', name: 'Фиджи' },
    { iso: 'PH', dial: '63', name: 'Филиппины' },
    { iso: 'FI', dial: '358', name: 'Финляндия' },
    { iso: 'FK', dial: '500', name: 'Фолклендские острова' },
    { iso: 'FR', dial: '33', name: 'Франция' },
    { iso: 'GF', dial: '594', name: 'Французская Гвиана' },
    { iso: 'PF', dial: '689', name: 'Французская Полинезия' },
    { iso: 'TF', dial: '262', name: 'Французские Южные территории' },
    { iso: 'HR', dial: '385', name: 'Хорватия' },
    { iso: 'CF', dial: '236', name: 'Центральноафриканская Республика' },
    { iso: 'TD', dial: '235', name: 'Чад' },
    { iso: 'ME', dial: '382', name: 'Черногория' },
    { iso: 'CZ', dial: '420', name: 'Чехия' },
    { iso: 'CL', dial: '56', name: 'Чили' },
    { iso: 'CH', dial: '41', name: 'Швейцария' },
    { iso: 'SE', dial: '46', name: 'Швеция' },
    { iso: 'SJ', dial: '47', name: 'Шпицберген и Ян-Майен' },
    { iso: 'LK', dial: '94', name: 'Шри-Ланка' },
    { iso: 'EC', dial: '593', name: 'Эквадор' },
    { iso: 'GQ', dial: '240', name: 'Экваториальная Гвинея' },
    { iso: 'ER', dial: '291', name: 'Эритрея' },
    { iso: 'EE', dial: '372', name: 'Эстония' },
    { iso: 'ET', dial: '251', name: 'Эфиопия' },
    { iso: 'ZA', dial: '27', name: 'ЮАР' },
    { iso: 'SS', dial: '211', name: 'Южный Судан' },
    { iso: 'JM', dial: '1876', name: 'Ямайка' },
    { iso: 'JP', dial: '81', name: 'Япония' },
];

// Страна по умолчанию при первом открытии выбора — Россия, наиболее
// вероятный вариант для аудитории void-code.ru.
export const DEFAULT_COUNTRY = COUNTRIES.find(c => c.iso === 'RU') || COUNTRIES[0];

export const findCountryByIso = (iso) => COUNTRIES.find(c => c.iso === iso) || DEFAULT_COUNTRY;
